### ISSUE TITLE
Types not exported correctly?

### ISSUE THREAD

**Issue by magnattic** [thomasbrodusch/vitest-fail-on-console#10]
## Bug description
When importing this into a TS file, I get the following warning by typescript:
![image](https://github.com/thomasbrodusch/vitest-fail-on-console/assets/7560166/7a889229-fa63-41f7-94ed-c3de92597c47)

> Could not find a declaration file for module 
myproject/node_modules/.pnpm/vitest-fail-on-console@0.4.0/node_modules/vitest-fail-on-console/dist/vitest-fail-on-console.es.js implicitly has an `any` type.
> There are types at myproject/node_modules/vitest-fail-on-console/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'vitest-fail-on-console library may need to update its package.json or typings.

#### Description
I think the problem might be that you define your package.json like this:
```
  "exports": {
    ".": {
      "import": "./dist/vitest-fail-on-console.es.js",
      "require": "./dist/vitest-fail-on-console.umd.js"
    }
  },
  "types": "./dist/index.d.ts",
```

This could solve it:
```
  "exports": {
    ".": {
      "import": "./dist/vitest-fail-on-console.es.js",
      "require": "./dist/vitest-fail-on-console.umd.js",
      "types": "./dist/index.d.ts",
    }
   "types": "./dist/index.d.ts",
  },
```

#### Expected outcome
No type errors.

#### More info
Check out this thread: https://github.com/microsoft/TypeScript/issues/52363
And this helpful tool to check if it's set up correctly: https://arethetypeswrong.github.io/?p=vitest-fail-on-console%400.4.0

**Comment by thomasbrodusch** [comment]
Thanks and congrats for your first PR on the repo @magnattic 🥳
New version `v0.4.1` including your fix now available on NPM!
