### ISSUE TITLE
Failure when using with react snapshot testing

### ISSUE THREAD

**Issue by swaroopsm** [thomasbrodusch/vitest-fail-on-console#15]
#### Description
The package doesn't seem to be working when the tests contain react snapshot testing. It fails with an error:
```
Cannot read properties of undefined (reading 'match')
```

(Probably a duplicate of https://github.com/thomasbrodusch/vitest-fail-on-console/issues/14)

Steps to reproduce:
- Create a new vite project by running: `npm create vite@latest`
- Install `vitest`, `testing-library`, `jsdom`

Here is my configuration:
```ts
// vite.config.ts

export default defineConfig({
  plugins: [react()],
  test: {
    globals: true,
    environment: "jsdom",
    setupFiles: "./src/setup-test.ts",
  },
});

```

```tsx
// App.test.tsx

import { render } from "@testing-library/react";
import "@testing-library/jest-dom";
import { expect, test } from "vitest";

import App from "./App";

test("<App />", () => {
  const result = render(<App />);

  expect(result).toMatchSnapshot();
});

```

Versions:
```
Node: v18.16.1
Vite: ^5.0.0
Vitest: ^0.34.6
```

#### Expected outcome
When I run `npx  vitest`, tests that contain snapshot testing must not throw an error and completes with a success.

#### Actual outcome
When I run `npx  vitest`, tests that contain snapshot testing are currently failing.

### Screenshots / Video / StackTrace

<img width="795" alt="image" src="https://github.com/thomasbrodusch/vitest-fail-on-console/assets/898602/7edf30b1-31c4-45c0-bc7a-f2c86db4150d">

**Comment by thomasbrodusch** [comment]
Hi @swaroopsm  do you still encounter this issue with the latest version `v0.6.2`?
