### ISSUE TITLE
Type error in 0.6.2

### ISSUE THREAD

**Issue by charliematters** [thomasbrodusch/vitest-fail-on-console#20]
## Bug description
Type error in 0.6.2 (not present in 0.5.1)

#### Description
The import path for the types is incorrect, causing type errors on the `silenceMessage` config option.

In `node_modules/vitest-fail-on-console/dist/src/index.d.ts`, there is this import:
```
import { VitestFailOnConsoleFunction } from './src/types';
```
...however there is no `src` folder - the `types.d.ts` file is a sibling

**Comment by thomasbrodusch** [comment]
Thanks @charliematters for raising this issue!
It has been fixed in commit f4e4a2104265c46e8a5aa0c3c95e1b2f2228ce3f and published on `v0.6.3` available on NPM 👌

**Comment by charliematters** [comment]
That's great - thanks!
