### ISSUE TITLE
Clean up package.json

### ISSUE THREAD

**Issue by romadryud** [thomasbrodusch/vitest-fail-on-console#21]
## Feature description

- Clean up package.json from unused packages.
- Add lockfile from preferred package manager.
- Consider specifying a specific version `1.0.4` instead of minor releases: `^1.0.4`

#### Description

Hi, thank you for the package. I would like to clean up `package.json` from unused packages, such as `node-stdlib-browser` and `tslib` along with adding a lock file. 

Pros:
- removing packages -> less bundle size
- adding lockfile -> every contributor will have the same version of the dependency packages
- specifying specific version -> more control on which version is installed; unfortunately, not all libraries use semantic versioning so is more about possible unwanted bugs in the future.

Cons:
- specifying a specific version -> more updates needed in case the library in dependency is updated, after cleaning up we will have only `chalk` which don't get updates often.

#### Expected outcome

Proposed pull request is accepted after discussion :)

**Comment by thomasbrodusch** [comment]
Hi @romadryud good idea!
If you want to suggest a PR related to this let's do this 🚀
