### ISSUE TITLE
Eslint report "Unable to resolve path to module 'vitest-fail-on-console'." when importing

### ISSUE THREAD

**Issue by esquevin** [thomasbrodusch/vitest-fail-on-console#6]
## Bug description
Lib works as expected, but eslint complains that the file cannot be resolved

#### Description

Got a lint error that is failing my CI

#### Expected outcome

no lint errors

Issue seems to be that the entry points of the lib are declared using "exports" (which is great) but are lacking a "main" definition.

Adding `"main": "./dist/vitest-fail-on-console.es.js",` seems to solve the issue

In any case, thank you for your work =)

**Comment by thomasbrodusch** [comment]
Hi @esquevin !
Thanks for opening a new issue on this repo 😀

Can you give more details so I can try to reproduce this issue?
Because when I run linting on the project with `eslint` using `yarn lint`, it shows no errors.

ps: sorry for the late reply, I was on holiday.
