### ISSUE TITLE
feat: failOnConsole should print the log right away

### ISSUE THREAD

**Issue by maxpatiiuk** [thomasbrodusch/vitest-fail-on-console#61]
## Feature description

failOnConsole() by default will capture all errors, and output them at the end of the test.

However, that has undesirable consequences:
- If you are debugging the test, seeing the console errors right away is very helpful.
- If the test is going to time out, the developer won't see the console message until after the timeout. By logging the error right away, you see what might have caused the test to timeout, without having to wait for the timeout.
- Even though failOnConsole() tries to capture the stack trace and output it when logging the message again at the end, that still does not preserve the stack trace of async actions (i.e `.catch(console.error)`) (see https://stackoverflow.com/q/59726106/8584605 for more details).
  
  At the same time, browser DevTools have features for piecing together async stack traces - but this "piecing together" seems to only happen when you let the console error through naturally - accessing the `new Error()` stack trace does not include this. So having the console error logged right away is very helpful.

For the above reasons, I propose that failOnConsole should print the message right away.

---

Given the following comment in the failOnConsole's code, I think this change will still be fine - you let the console messages though, but then throw an error at the end saying that unexpected console messages got printed during the test execution.

https://github.com/thomasbrodusch/vitest-fail-on-console/blob/d6b7b3bcb5758862d7f5470d308b16339eef3e2e/src/index.ts#L89

The error message at the end of the test doesn't need to include the console messages again. But if for some reason that I am not aware of that is necessary, then having the console message printed twice is still less bad than the current behavior (see the reasons listed above).

### Workaround

I am using the `silenceMessage` option to "hack" failOnConsole into the correct behavior:

```ts
  const originalConsole = { ...console };
  failOnConsole({
    silenceMessage(message, methodName) {
      originalConsole[methodName](message);
      return false;
    },
  });
```

**Comment by thomasbrodusch** [comment]
Hi @maxpatiiuk thanks for raising an issue!

In my opinion, this is more like an improvement request rather than a critical issue.
That said, you can totally make a  new PR proposal ;)

**Comment by thomasbrodusch** [comment]
@maxpatiiuk I close this issue :)

**Comment by maxpatiiuk** [comment]
Excuse me for the delay - I was sidetracked with work matters.

In this issue I proposed two solutions.
Here are the two PRs for them:
- https://github.com/thomasbrodusch/vitest-fail-on-console/pull/69
- https://github.com/thomasbrodusch/vitest-fail-on-console/pull/70/

I will leave it to you to decide which of the two solutions is better.
