### ISSUE TITLE
How this project is different from jest-fail-on-console?

### ISSUE THREAD

**Issue by Maxim-Mazurok** [thomasbrodusch/vitest-fail-on-console#7]
This appears to be a copy of https://github.com/ValentinH/jest-fail-on-console that may or may not include vitest-specific adjustments.

It's hard to compare because it doesn't appear as a fork on GitHub, and there's no description/log of what was changes (except for names).

Also since it's not connected to the original project - it's not clear if upstream commits/fixes are being merged into this one.

I've tried using `jest-fail-on-console` in my Vue3+TS+Vitest project and it appears to be working, so considering all that I'll be using `jest-fail-on-console`.

I'm not a licensing specialist, but in https://github.com/ValentinH/jest-fail-on-console/blob/main/LICENSE it says "...requiring preservation of copyright and license notices..." yet in https://github.com/thomasbrodusch/vitest-fail-on-console/blob/develop/license there's no mention of the original project or Valentin Hervieu

**Comment by thomasbrodusch** [comment]
Hi @Maxim-Mazurok 
Thanks for your comment on this repo!

> This appears to be a copy of https://github.com/ValentinH/jest-fail-on-console that may or may not include vitest-specific adjustments.

There is several changes between `jest-fail-on-console` and `vitest-fail-on-console`: 
- fully typed functions, arguments, and variables using TypeScript `types` and `enums` - [here](https://github.com/thomasbrodusch/vitest-fail-on-console/blob/develop/src/types.ts)
- refactoring of the whole codebase - [here](https://github.com/thomasbrodusch/vitest-fail-on-console/blob/develop/src/index.ts)
- refactoring of test/specs - [here](https://github.com/thomasbrodusch/vitest-fail-on-console/blob/develop/tests/index.spec.ts)
- credits to the original project [here](https://github.com/thomasbrodusch/vitest-fail-on-console#credits)

That said, the fact that it is interesting to log those differences somewhere is a nice idea that I'll do👌 

---
> I've tried using jest-fail-on-console in my Vue3+TS+Vitest project and it appears to be working, so considering all that I'll be using jest-fail-on-console.

If it works for you good! 
But if there are any changes in the future that his directly impacted to fit `jest` environment, there is some chance that it will break your stuff, as you're using Vitest.
This repository was been developed and publish for that specific reason and you're free to use it or not :)

**Comment by Maxim-Mazurok** [comment]
Thanks for the info, I did realize after opening this that it was rewritten to TS, but missed the credits section, thanks for pointing me to it!
One of the devs added this package and I was doing a code review of that change so had to be wearing a "suspicious" hat :)

**Comment by thomasbrodusch** [comment]
You're more than welcome @Maxim-Mazurok !
Thanks for using [vitest-fail-on-console](https://github.com/thomasbrodusch/vitest-fail-on-console) on your project 🫶  

If you have further questions in the future don't hesitate to open a new ticket :)

**Comment by thomasbrodusch** [comment]
@Maxim-Mazurok https://github.com/thomasbrodusch/vitest-fail-on-console#how-this-project-is-different-from-jest-fail-on-console
