### ISSUE TITLE
Pinned dependency of chalk

### ISSUE THREAD

**Issue by ondrejsevcik** [thomasbrodusch/vitest-fail-on-console#79]
I've noticed that the `chalk` dependency is pinned to a specific version. It would make sense to specify it with the `^` range. That way, npm can dedupe the versions in the dependency graph.

https://github.com/thomasbrodusch/vitest-fail-on-console/blob/f1643ae7c556bc56a997867303ac5a6334c641e0/package.json#L57

**Comment by thomasbrodusch** [comment]
Thanks @ondrejsevcik ! 
I will push a PR to improve this 👍

**Comment by thomasbrodusch** [comment]
Fixed in https://github.com/thomasbrodusch/vitest-fail-on-console/commit/42024d1e5b2e82184b68fb750889c6eb09cd84ef @ondrejsevcik

**Comment by ondrejsevcik** [comment]
Will this improvement be released?
